version: '0.2'
sources:
- database: local
  link: ''
  type: local
  branch: master
  cache_path: ''
  cache_timestamp: ''
  filters: null
- database: poo
  link: https://github.com/qxcodepoo/arcade.git
  type: clone
  branch: master
  cache_path: ''
  cache_timestamp: '2025-12-02 15:57:08'
  filters: null
expanded:
- poo@campanha-principal
- poo@bloco_d-crud-com-mapas-e-enumerações
tasks:
  poo@zoo: '{human:sim__monitor_, iagen:nao_, guide:sim__aula_, other:nao, study:90}'
flags:
  quests: 0
  tracks: 0
  tasks: 0
  graph: 1
  xray: 0
lang: py
selected: poo@agenda
